Refactoring and extracting common functions

diff --git a/meta-enapter-core/recipes-core/initrdscripts/files/password-reset b/meta-enapter-core/recipes-core/initrdscripts/files/password-reset
--- a/meta-enapter-core/recipes-core/initrdscripts/files/password-reset
+++ b/meta-enapter-core/recipes-core/initrdscripts/files/password-reset
@@ -2,6 +2,12 @@
 # SPDX-FileCopyrightText: 2023 Enapter <developers@enapter.com>
 # SPDX-License-Identifier: Apache-2.0
 
+. /usr/share/scripts/enapter-variables
+
+ensure_sync() {
+  sync; sync; sync
+}
+
 passwordreset_enabled() {
   if [ -z ${bootparam_do_password_reset} ]; then
     return 1
@@ -10,18 +16,14 @@ passwordreset_enabled() {
 }
 
 passwordreset_run() {
-    local userspace_label="enp-data-disk"
-    local userspace_device="/dev/disk/by-label/$userspace_label"
-    local userspace_mountdir="/user"
-    local password_file="/etc/enapter/enapter-superuser-password.env"
     local disk_opts="defaults,rw,nodev,nosuid"
 
-    if [ -L ${userspace_device} ]; then
-      mkdir -p $userspace_mountdir
-      mount "$userspace_device" -t auto -o "$disk_opts" "$userspace_mountdir" || fatal "Failed to mount userspace disk"
-      rm -f "$userspace_mountdir$password_file"
-      sync; sync; sync
-      umount $userspace_mountdir || fatal "Failed to unmount userspace disk"
+    if [ -L ${hdd_data_device} ]; then
+      mkdir -p $user_fs_mount
+      mount "$hdd_data_device" -t auto -o "$disk_opts" "$user_fs_mount" || fatal "Failed to mount userspace disk"
+      rm -f "$user_fs_mount$etc_enapter/$enapter_superuser_password_env_file"
+      ensure_sync
+      umount $user_fs_mount || fatal "Failed to unmount userspace disk"
       info "Password reset done"
     else
       info "No userspace disk found, nothing to reset"
