Fix overlayfs stacking order
According to documentation:

Multiple lower layers can now be given using the the colon (":") as a
separator character between the directory names.  For example:

  mount -t overlay overlay -olowerdir=/lower1:/lower2:/lower3 /merged

As the example shows, "upperdir=" and "workdir=" may be omitted.  In
that case the overlay will be read-only.

The specified lower directories will be stacked beginning from the
rightmost one and going left.  In the above example lower1 will be the
top, lower2 the middle and lower3 the bottom layer.

diff --git a/meta-enapter-core/recipes-core/initrdscripts/files/rootfs b/meta-enapter-core/recipes-core/initrdscripts/files/rootfs
--- a/meta-enapter-core/recipes-core/initrdscripts/files/rootfs
+++ b/meta-enapter-core/recipes-core/initrdscripts/files/rootfs
@@ -236,7 +236,7 @@ rootfs_run() {
             mount -o loop -t squashfs "$layer_image" "$layers_ro_mount_base_dir/$layer_name"
 
             if [ -d "$layers_ro_mount_base_dir/$layer_name/rootfs" ]; then
-               root_additional_lowerdirs="$root_additional_lowerdirs:$layers_ro_mount_base_dir/$layer_name/rootfs"
+               root_additional_lowerdirs="$layers_ro_mount_base_dir/$layer_name/rootfs:$root_additional_lowerdirs"
             fi
         fi
     done
@@ -249,7 +249,7 @@ rootfs_run() {
     degub "rootfs overlayfs additional lowerdirs: $root_additional_lowerdirs"
 
     mkdir -p "$root_rw_mount/upperdir" "$root_rw_mount/work"
-    mount -o "lowerdir=$root_ro_mount$root_additional_lowerdirs,upperdir=$overlayfs_upperdir,workdir=$overlayfs_workdir" -t overlay overlay "$ROOTFS_DIR" || fatal "Failed to mount overlayfs root fs"
+    mount -o "lowerdir=$root_additional_lowerdirs$root_ro_mount,upperdir=$overlayfs_upperdir,workdir=$overlayfs_workdir" -t overlay overlay "$ROOTFS_DIR" || fatal "Failed to mount overlayfs root fs"
 
     debug "overlayfs mounted"
 
